version: '3'

services:
  mariadb:
    build: './MariaDB/.'
    image: mariadb:api_image
    container_name: 'api_container'
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=1234'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
