version: '3.5'
services:
    marmantenimiento:
        image: 'mariadbapi'
        build: ./MariaDB/.
        container_name: 'cmariaapi'
        environment: 
            - 'MYSQL_ROOT_PASSWORD=1234'
        ports:
            - '3306:3306'
        volumes:
            - /home/mariadbSiemaVol:/var/lib/mysql
        networks: 
            mantenimiento_net:
                ipv4_address: 172.25.0.28

networks: 
    mantenimiento_net:
        ipam:
            driver: default
            config:
            - subnet: 172.25.0.0/16

